services:
  app:
    image: backsoulsdle:latest
    container_name: springback
    restart: unless-stopped
    ports:
      - "4242:4242"
    env_file:
      - .env
    networks:
      - caddy

networks:
  caddy:
    external: true