# Comentario
server:
    address: ${SERVER_ADDRESS}
    port: ${SERVER_PORT}

spring:
    application:
        name: fct_bbdd
    datasource:
        url: ${DB_URL}
        driverClassName: com.mysql.cj.jdbc.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
            #ddl-auto: create
            #ddl-auto=create-drop
            #ddl-auto=none
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 30000
                    timeout: 30000
                    writetimeout: 30000

logging:
    file:
        name: logs/app.log